name: Build and Deploy
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install and Build
              run: |
                  npm ci
                  npm run build -- --base-href /ng-heroes-app/
                  touch dist/ng-heroes-app/.nojekyll
                  echo 'ceyhan.cloud' > dist/ng-heroes-app/CNAME

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.3
              with:
                  branch: gh-pages # The branch the action should deploy to.
                  folder: dist/ng-heroes-app # The folder the action should deploy.
